language: python
python:
  - "3.6"
# command to install dependencies
install:
    - pip install poetry
    - poetry install
env:
  - TESTS_TO_RUN=tests/test_tool.py
# command to run tests
script:
  - pytest $TESTS_TO_RUN